### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by Ars-Vitae** [chrisfue/MaintenanceMonitor#5]
Track your development process by updating your Kanban board and write at least one unit tests for every requirement. A Continuous Integration pipeline that produces the finished software artifact should be implemented as well.

Document

> - the whole process
> - the user stories
> - the repository URL (it has to be public)
> - the usage of the software
> -

**Comment by Ars-Vitae** [comment]
we create a Google Doc with our documented parts and pictures of the project.
with: 
-HowTo
-With UserTest
-with Documentation of the Developing Process
-Description
-ec.

**Comment by Einheit21** [comment]
Finished Project documentation and included the git-link
